export const siteCopy = {
  en: {
    brand: "Dagegme",
    nav: [
      { label: "How It Works", href: "/#how-it-works" },
      { label: "Professionals", href: "/professionals" },
    ],
    languageLabel: "Language",
    themeLabel: "Theme",
    light: "Light",
    dark: "Dark",
    wishlist: "Wishlist",
    wishlistTitle: "Your wishlist",
    wishlistEmpty:
      "Your wishlist is empty. Save professionals you like using the heart icon.",
    removeFromWishlist: "Remove",
    viewListing: "View",
    close: "Close",
    listingDetails: {
      close: "Close details",
      city: "City",
      about: "About",
      descriptionFallback: "More details will be added soon.",
      save: "Add to wishlist",
      saved: "Saved to wishlist",
      link: "Showreel {number}",
      gallery: "Gallery",
      openImage: "Open gallery image {number}",
      expandImage: "Expand selected photo",
      closeGallery: "Close expanded gallery",
      previousPhoto: "Previous photo",
      nextPhoto: "Next photo",
    },
    heroEyebrow: "Dagegme.ge",
    heroTitleTop: "Plan your ideal",
    heroTitleAccent: "wedding beautifully",
    heroText:
      "Find photographers, videographers, halls, bands, and trusted professionals for your special day.",
    processTitle: "How it works",
    processSteps: [
      { icon: "search", title: "Find the service you need" },
      { icon: "shortlist", title: "Compare professionals" },
      { icon: "chat", title: "Message and choose easily" },
      { icon: "celebrate", title: "Enjoy your event" },
    ],
    about: {
      eyebrow: "About Dagegme",
      title: "A beautiful celebration starts with a calmer way to plan",
      text: "Dagegme brings the people, places, and details behind a memorable event into one thoughtful space. Explore at your own pace, save what feels right, and build a celebration that truly feels like yours.",
      statement: "Less searching. More celebrating.",
      tags: ["People", "Places", "Moments"],
      values: [
        {
          icon: "people",
          title: "Inspiring professionals",
          text: "Discover talented people across every essential category.",
        },
        {
          icon: "place",
          title: "Everything in one place",
          text: "Keep your options close and your planning beautifully simple.",
        },
        {
          icon: "heart",
          title: "Made for your day",
          text: "Choose the details that match your story, taste, and vision.",
        },
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Let’s talk about your celebration",
    },
    footer: {
      tagline:
        "A thoughtful place to discover the people and details behind your most meaningful celebrations.",
      navigationLabel: "Explore",
      links: [
        { label: "Categories", href: "/#categories" },
        { label: "How it works", href: "/#how-it-works" },
        { label: "About us", href: "/#about" },
      ],
      calloutTitle: "Your celebration starts here",
      calloutText:
        "Find the right professionals and keep every favorite close.",
      calloutAction: "Explore categories",
      note: "Made for moments worth remembering.",
    },
    professionals: {
      eyebrow: "Explore the community",
      title: "Everything you need, all in one place",
      text: "Browse every professional and service by category. Swipe through each collection, save your favorites, and shape the celebration you have in mind.",
      loading: "Loading professionals...",
      error:
        "We could not load the professionals right now. Please try again shortly.",
      categoryTitles: {
        photographers: "Photographers",
        videographers: "Videographers",
        bands: "Bands",
        djs: "DJs",
        presenters: "Presenters",
        halls: "Halls",
        "rental-cars": "Rental cars",
      },
      categoryPage: {
        back: "All professionals",
        subtitle: "Explore every option and save the ones that feel right.",
        cityLabel: "Filter by city",
        allCities: "All cities",
        results: "{count} results",
        empty: "No professionals match this city yet.",
      },
    },
  },
  ka: {
    brand: "Dagegme",
    nav: [
      { label: "როგორ მუშაობს", href: "/#how-it-works" },
      { label: "პროფესიონალები", href: "/professionals" },
    ],
    languageLabel: "ენა",
    themeLabel: "თემა",
    light: "თეთრი",
    dark: "მუქი",
    wishlist: "სურვილების სია",
    wishlistTitle: "შენი სურვილების სია",
    wishlistEmpty:
      "სურვილების სია ცარიელია. სასურველი პროფესიონალები გულის ნიშნით შეინახე.",
    removeFromWishlist: "წაშლა",
    viewListing: "ნახვა",
    close: "დახურვა",
    listingDetails: {
      close: "დეტალების დახურვა",
      city: "ქალაქი",
      about: "შესახებ",
      descriptionFallback: "დეტალები მალე დაემატება.",
      save: "სურვილების სიაში დამატება",
      saved: "შენახულია სურვილების სიაში",
      link: "საიმიჯო კლიპი {number}",
      gallery: "გალერეა",
      openImage: "გალერეის სურათის გახსნა {number}",
      expandImage: "არჩეული ფოტოს გადიდება",
      closeGallery: "გადიდებული გალერეის დახურვა",
      previousPhoto: "წინა ფოტო",
      nextPhoto: "შემდეგი ფოტო",
    },
    heroEyebrow: "Dagegme.ge",
    heroTitleTop: "დაგეგმე იდეალური",
    heroTitleAccent: "ქორწილი მარტივად",
    heroText:
      "იპოვე ფოტოგრაფი, ვიდეოგრაფი, ბენდი, დარბაზი და სხვა პროფესიონალები შენი ღონისძიებისთვის.",
    processTitle: "როგორ მუშაობს",
    processSteps: [
      { icon: "search", title: "აირჩიე კატეგორია" },
      { icon: "shortlist", title: "მოიძიე პროფესიონალები და აარჩიე" },
      { icon: "chat", title: "დაგვიკავშირდი და დაჯავშნე +99551288483" },
      { icon: "celebrate", title: "ისიამოვნე ღონისძიებით" },
    ],
    about: {
      eyebrow: "Dagegme-ს შესახებ",
      title: "ლამაზი დღესასწაული მშვიდი დაგეგმვით იწყება",
      text: "Dagegme ერთ სივრცეში აერთიანებს ადამიანებს, ადგილებსა და დეტალებს, რომლებიც დაუვიწყარ ღონისძიებას ქმნის. დაათვალიერე შენს რიტმში, შეინახე რაც მოგწონს და შექმენი დღე, რომელიც ნამდვილად შენია.",
      statement: "ნაკლები ძიება. მეტი ზეიმი.",
      tags: ["ადამიანები", "ადგილები", "მომენტები"],
      values: [
        {
          icon: "people",
          title: "გამორჩეული პროფესიონალები",
          text: "აღმოაჩინე ნიჭიერი ადამიანები ყველა საჭირო კატეგორიაში.",
        },
        {
          icon: "place",
          title: "ყველაფერი ერთ სივრცეში",
          text: "შეინახე არჩევანი და დაგეგმვის პროცესი მარტივი გახადე.",
        },
        {
          icon: "heart",
          title: "შექმნილი შენი დღისთვის",
          text: "აირჩიე დეტალები, რომლებიც შენს ისტორიას და გემოვნებას ერგება.",
        },
      ],
    },
    contact: {
      eyebrow: "კონტაქტი",
      title: "მოგვიყევი შენი დღესასწაულის შესახებ",
    },
    footer: {
      tagline:
        "ერთი სივრცე, სადაც შენი მნიშვნელოვანი დღის პროფესიონალებსა და განსაკუთრებულ დეტალებს აღმოაჩენ.",
      navigationLabel: "აღმოაჩინე",
      links: [
        { label: "კატეგორიები", href: "/#categories" },
        { label: "როგორ მუშაობს", href: "/#how-it-works" },
        { label: "ჩვენ შესახებ", href: "/#about" },
      ],
      calloutTitle: "შენი დღესასწაული აქ იწყება",
      calloutText: "იპოვე სასურველი პროფესიონალები და შეინახე ყველა რჩეული.",
      calloutAction: "ნახე კატეგორიები",
      note: "შექმნილი დაუვიწყარი მომენტებისთვის.",
    },
    professionals: {
      eyebrow: "აღმოაჩინე ჩვენი სივრცე",
      title: "ყველაფერი, რაც გჭირდება, ერთ სივრცეში",
      text: "დაათვალიერე ყველა პროფესიონალი და მომსახურება კატეგორიების მიხედვით. გადაფურცლე კოლექციები, შეინახე რჩეულები და შექმენი შენთვის სასურველი დღესასწაული.",
      loading: "პროფესიონალები იტვირთება...",
      error:
        "პროფესიონალების ჩატვირთვა ვერ მოხერხდა. გთხოვ, სცადო მოგვიანებით.",
      categoryTitles: {
        photographers: "ფოტოგრაფები",
        videographers: "ვიდეოგრაფები",
        bands: "ბენდები",
        djs: "დიჯეები",
        presenters: "წამყვანები",
        halls: "დარბაზები",
        "rental-cars": "გასაქირავებელი მანქანები",
      },
      categoryPage: {
        back: "ყველა პროფესიონალი",
        subtitle: "დაათვალიერე ყველა ვარიანტი და შეინახე რჩეულები.",
        cityLabel: "ქალაქით გაფილტვრა",
        allCities: "ყველა ქალაქი",
        results: "{count} შედეგი",
        empty: "ამ ქალაქში პროფესიონალები ჯერ არ მოიძებნა.",
      },
    },
  },
};
